# Generated by Django 4.1.6 on 2023-02-02 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="drink",
            old_name="discription",
            new_name="description",
        ),
    ]
