# Generated by Django 4.1.6 on 2023-02-02 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_rename_discription_drink_description"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Drink",
            new_name="Books",
        ),
    ]
